---
title: "p8105_hw2_by2287"
output: github_document
---

```{r setup, include = FALSE}
library(tidyverse)
library(readxl)
```


## Problem 1 

### Read in & clean the trash-wheel dataset
```{r read in & clean in trash_wheel data}
trash_wheel = read_xlsx(
                  path = "./data/Trash-Wheel-Collection-Totals-8-6-19.xlsx", 
                  sheet = 1, 
                  skip = 1,
                  range = cell_cols("A:N")) %>% 
	        janitor::clean_names() %>% 
          filter(dumpster != "NA") %>% 
            mutate(
              sports_balls = round(sports_balls),
              sports_balls = as.integer(sports_balls)
            ) 
```


### Read in & clean the precipitation data for 2017 & 2018
```{r read in 2017 & 2018 precipitation data}
precip_2017 = read_xlsx(
                  path = "./data/Trash-Wheel-Collection-Totals-8-6-19.xlsx", 
                  sheet = "2017 Precipitation",
                  skip = 1) %>% 
  janitor::clean_names() %>% 
  drop_na(month) %>% 
  mutate(year = 2017) %>% 
  relocate(year)


precip_2018 = read_xlsx(
                  path = "./data/Trash-Wheel-Collection-Totals-8-6-19.xlsx", 
                  sheet = "2018 Precipitation", 
                  skip = 1) %>% 
  janitor::clean_names() %>% 
  drop_na(month) %>% 
  mutate(year = 2018) %>% 
   relocate(year)
                  

precip_df = bind_rows(precip_2017, precip_2018)


precip_df = precip_df %>% 
      mutate(month = month.name[month])
```



